### ISSUE TITLE
Expose datatables customisation options

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#13]
From https://datatables.net/reference/option/ we currently can't control the display of the table visualisation - it'd be nice to be able to set the page length, permit column sorts, show/hide the search box etc

**Comment by tobybellwood** [comment]
Also consider adding the ability to render input within datatables:
e.g. https://datatables.net/manual/data/renderers#Number-helper

**Comment by jorgegc** [comment]
Closing this now that #25 has been merged.
