### ISSUE TITLE
Drupal 7: govcms_ckan and the DVF

### ISSUE THREAD

**Issue by JamesWilmot** [govCMS/dvf#17]
I would be interested in a discussion around how the DVF will fit around govcms_ckan and whether there are any plans to merge/backport DVF. 

Personally, I would imagine there are a number of advantages to focusing efforts on one ecosystem of modules with those modules offering something for both D7 and D8.

**Comment by jez500** [comment]
DVF now supports all functionality that govcms_ckan did, no plans to backport dvf to Drupal 7 as it will be EOL shortly
