### ISSUE TITLE
Moving towards a release

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#21]
Now that @jez500 has moved this forward a bit - let's get our heads around to thinking what we'd need to do to take this to a first alpha/beta release.

I'm thinking as a wish list:

- getting the additional table enhancements in
- moving to support D3 v5 (c3 ^0.6.0)
- support for views integration
- consume json data format

Thoughts @jorgegc & @jez500?

**Comment by jez500** [comment]
Hey @tobybellwood 

I think the key to getting a release out is ensuring there will be no API changes for any other modules interacting with DVF probably json support and views integration would solidify this as they both assume the API is solid.

Adding Json should be relatively simple but views integration would be a far larger task.

fyi @jorgegc

**Comment by jorgegc** [comment]
Hi @tobybellwood, I have to echo what @jez500 said. Everything on that list except the Views integration should be relatively simple. The module's API is fairly stable right now and that is what we should focus on for the first release.

Views integration will be a game changer and I would like us to plan it out properly before diving into it. We need to leave something for people to look forward to in 8.x-2.0 :-)

**Comment by tobybellwood** [comment]
cool cool - happy to collect a hit list and see what we can do!  Any other things that you think we should include?

**Comment by jorgegc** [comment]
Hi @tobybellwood, sorry for the delayed response. I think we already have enough to make a really good 8.x-1.0 release.

If you think about all the features already available in the module and sub-modules, they cover most of the use cases. Having said that, it is probably a good idea to start thinking about the roadmap so we can start planning/architecting and estimate effort.

**Comment by jez500** [comment]
Shiny stable 2.0 release now out in the wild https://www.drupal.org/project/dvf

🍾🍻🙂

**Comment by stooit** [comment]
Congrats all! 🚀🍻
