### ISSUE TITLE
Allow a data file to be reused.

### ISSUE THREAD

**Issue by simesy** [govCMS/dvf#28]
I think this makes sense through some sort of media type. This type could then be selected as the source for the field (when adding content).

**Comment by jeremy-doghouse** [comment]
You should be able to do that with a [media](https://www.drupal.org/docs/8/core/modules/media)
Add a dvf field to a custom media entity then use the media browser to add/reuse data on other entities

**Comment by simesy** [comment]
Thanks I'll test that
