### ISSUE TITLE
Add in JSON as a datasource

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#4]
create dvf_json submodule to handle formatted JSON

**Comment by tobybellwood** [comment]
Couple of sample datasets:

**Socrata (SODA) API (e.g. data.act.gov.au or data.melbourne.vic.gov.au):**
https://www.data.act.gov.au/Infrastructure-and-Utilities/CBRfree-Wi-Fi-Monthly-Reports/sptb-jhn6/data
https://www.data.act.gov.au/resource/3ics-cdy4.json

https://data.melbourne.vic.gov.au/Property-Planning/Median-House-Prices-By-Type-and-Sale-Year/i8px-csib/data
https://data.melbourne.vic.gov.au/resource/9h32-xid2.json

**Comment by tobybellwood** [comment]
**OpenDataSoft (e.g. data.opendatasoft.com):**
https://data.opendatasoft.com/explore/dataset/share-of-the-top-income-in-the-total-income-canada-australia-new-zealand-denmark@public/
https://data.opendatasoft.com/api/records/1.0/search/?dataset=share-of-the-top-income-in-the-total-income-canada-australia-new-zealand-denmark%40public

**Comment by jorgegc** [comment]
Closing this now that #23 has been merged.
