### ISSUE TITLE
Adjust permissions required to view help tips

### ISSUE THREAD

**Issue by KatieAK-enviro** [govCMS/dvf#49]
Users require the administer site configuration permission to view the help tips when setting up DVF charts. This permission is not suitable for content editors, so many of our users can't access these tips. Is it possible to adjust the permissions required so that non-administrator users can also benefit from the help information?

**Comment by rob-duplock** [comment]
Thanks @KatieAK-enviro this has now been fixed on the "develop" branch. Please see "Merge pull request #50" - https://github.com/govCMS/dvf/commits/develop

**Comment by KatieAK-enviro** [comment]
Thanks @rob-duplock
