### ISSUE TITLE
Allow multiple display javascript frameworks

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#5]
Currently supporting c3 and datatables, but possibly abstract on top of jquery.dvfCharts.js for c3 specifically, and then we can support plot.ly/highcharts etc in future.

**Comment by jez500** [comment]
This is possible and largely documented here https://github.com/govCMS/dvf/wiki/Adding-New-Visualisations

New visualisations using a different FE library should probably be added via an additional module to avoid DVF getting too bloated with external libraries (eg DVF Plotly or something). Kinda need some specific examples + use cases  to proceed though

With the move to billboard,js we now have a heap more visualisations OOTB with DVF including radar, scatter, bubble, pie & donut charts https://naver.github.io/billboard.js/demo
