### ISSUE TITLE
Error: Class 'Flow\JSONPath\JSONPath' not found in Drupal\dvf_json\Plugin\Visualisation\Source\JsonFile->getRecords()

### ISSUE THREAD

**Issue by klonos** [govCMS/dvf#55]
This issue has been reported in the GovCMS Service Desk.

> We've observed issues in using the DVF module functionality that allows data visualisations to be created from JSON data sources. I've asked our vendor to investigate (Doghouse Agency, who are also the maintainers of DVF), and they have reported that the error we receive is related to a missing dependency.
>
>Their comments: 
>
>>I checked the error logs after following what you did in the video, the error is as follows:

```
Error: Class 'Flow\JSONPath\JSONPath' not found in Drupal\dvf_json\Plugin\Visualisation\Source\JsonFile->getRecords() (line 165 of /app/web/modules/custom/dvf/dvf_json/src/Plugin/Visualisation/Source/JsonFile.php)
```

> Because `flow/jsonpath` is [a dependency](https://github.com/govCMS/dvf/blob/2.x/composer.json#L27) of the DVF module, it should have been automatically installed when DVF was installed. However, because it does not exist, this leads us to believe GovCMS have not installed the DVF module correctly (using composer).
>
>Could you please confirm whether the module has been installed correctly? This module is in use across several sites, but could be investigated on https://awe-white.govcms.gov.au/ in the first instance.

**Comment by jez500** [comment]
This has been fixed previously and now updated to the latest version of JSONPath https://github.com/govCMS/dvf/commit/9724d772a7930bd7783574fb300b1642648bd510
