### ISSUE TITLE
Create wiki to outline usage / host docco etc?

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#8]

**Comment by JamesWilmot** [comment]
I'm personally a big fan of [ReadTheDocs](http://docs.readthedocs.io/en/latest/getting_started.html) which is relatively easy to set-up and host through github pages.

While the github wiki is somewhat clunky, probably a good starting point.

**Comment by JamesWilmot** [comment]
Also this is an option: https://squidfunk.github.io/mkdocs-material/

**Comment by jez500** [comment]
Have kicked this off just using github wiki, most external 3rd party doc services can sync with this if really wanted to host it elsewhere, but wiki seems to be doing the job well for now https://github.com/govCMS/dvf/wiki
