### ISSUE TITLE
We need a logo!

### ISSUE THREAD

**Issue by tobybellwood** [govCMS/dvf#9]

**Comment by zuuritaly** [comment]
Hello @tobybellwood   ,
I'm a graphic designer and I design logos for open source projects. But I only do it for projects with licence, do you have one?

Usually I ask the following questions to assist me in the creative process:

Do you have something in your mind for the logo?
Do you want something specific for the logo?
What colors do you want in the logo?

With your answers I will design a logo for your project and if you like it you can keep it and used.

Best Regards

Zuur

**Comment by jez500** [comment]
Better late than never @tobybellwood ;) 

https://github.com/govCMS/dvf/wiki

**Comment by tobybellwood** [comment]
I guess my t-shirt is in the mail then?

**Comment by jez500** [comment]
An entire bag-o-swag for you mate ;)
